apiVersion: v1
kind: Service
metadata:
  namespace: snapee
  name: dev-backend-svc
spec:
  selector:
    app: dev-backend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: NodePort
