apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: snapee
  name: snapee-ingress
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "100m"
    # Security Headers
    nginx.ingress.kubernetes.io/x-frame-options: "SAMEORIGIN"
    nginx.ingress.kubernetes.io/content-type-nosniff: "true"
    nginx.ingress.kubernetes.io/x-xss-protection: "1; mode=block"
    
    # REWRITE LOGIC: This strips the prefix so /wallet/info becomes /info on the backend
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
  - host: devv-admin.snapecab.com
    http:
      paths:
      - path: /()(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: admin-frontend-svc
            port:
              number: 3000

  - host: devv-fleet.snapecab.com
    http:
      paths:
      - path: /admin(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: dev-microservice-campaign-svc
            port:
              number: 5001
      
      - path: /payment(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: payment-service-svc
            port:
              number: 5006
      
      - path: /wallet(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: wallet-service-svc
            port:
              number: 5003

      - path: /()(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: dev-backend-svc
            port:
              number: 5000
