apiVersion: v1
kind: Service
metadata:
  namespace: snapee
  name: wallet-service-svc
spec:
  selector:
    app: wallet-service
  ports:
    - protocol: TCP
      port: 5003
      targetPort: 8080
  type: ClusterIP
