apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: snapee
  name: dev-microservice-campaign
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dev-microservice-campaign
  template:
    metadata:
      labels:
        app: dev-microservice-campaign
    spec:
      imagePullSecrets:
        - name: aws-ecr-cred
      containers:
        - name: dev-microservice-campaign
          image: 297436350639.dkr.ecr.ap-south-1.amazonaws.com/snape/admin-service:latest
          ports:
            - containerPort: 5001
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
          envFrom:
            - secretRef:
                name: dev-microservice-campaign-secret
