apiVersion: v1
kind: Service
metadata:
  namespace: snapee
  name: admin-frontend-svc
spec:
  selector:
    app: admin-frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: NodePort
