apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: snapee
  name: payment-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      imagePullSecrets:
        - name: aws-ecr-cred
      containers:
        - name: payment-service
          image: 297436350639.dkr.ecr.ap-south-1.amazonaws.com/snape/payment-service:latest
          ports:
            - containerPort: 5006
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
          envFrom:
            - secretRef:
                name: payment-service-secret
