apiVersion: v1
kind: Service
metadata:
  namespace: snapee
  name: payment-service-svc
spec:
  selector:
    app: payment-service
  ports:
    - protocol: TCP
      port: 5006
      targetPort: 5006
  type: ClusterIP
